name: Build and Lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v5

      - name: Setup Node.js ğŸ“¦
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies ğŸ”§
        run: npm ci --include=dev

      - name: Lint ğŸš¨
        run: npm run lint

      - name: Type Check ğŸ”
        run: npx tsc -noEmit

      - name: Build code ğŸšš
        run: npm run build
